'use client';

import { Button, Flex, Center, Container, Modal, Paper, Stack, Text, Title } from '@mantine/core';
import { useWallet } from '@solana/wallet-adapter-react';
import { Create } from '@/components/Create/Create';
import { useDisclosure } from '@mantine/hooks';

export default function CreatePage() {
  const wallet = useWallet();
  const [moreInfoOpened, { open: openMoreInfoModal, close: closeMoreInfoModal }] = useDisclosure(false);

  return (
    <Container size="xl" pb="xl">
      {wallet.connected ? <Create /> :
        <Container size="sm">
          <Paper mt="xl">


          <Modal opened={moreInfoOpened} onClose={closeMoreInfoModal} centered withCloseButton>
  <Center my="xl">
    <Stack gap="md" align="center">
      <Title order={3}>More Information</Title>
      <Text size="sm">
        I am currently facing legal charges and have a trial scheduled for early July. 
        The charges include defrauding the company of approximately $2.9 million USD. 
        I need financial assistance to secure proper legal representation.
      </Text>
      <Text size="sm">
        This initiative aims to leverage the power of Liquid Staking Tokens (LSTs) for a risk-free charity. 
        By minting these tokens, you are not only supporting my legal defense but also demonstrating the potential 
        of blockchain technology to foster goodwill and community support.
      </Text>
      <Text size="sm">
        The proceeds from this initiative will come from the epoch rewards generated by the staked tokens. 
        I have ensured that all epoch rewards are directed to myself, without any mint or redeem fees, to maximize 
        the financial support received. Here are the specifics:
      </Text>
      <Text size="sm">
        - Epoch Fee: 1% <br />
        - SOL Deposit Fee: 0% <br />
        - Stake Withdrawal Fee: 0% <br />
        - Stake Deposit Fee: 0%
      </Text>
      <Text size="sm">
        Your support through minting these tokens will help cover my legal expenses and set a precedent for 
        how LSTs can be used for positive social impact. Thank you for standing with me during this challenging time.
      </Text>
      <Text size="sm">
        An example nft can be found at{' '}
        <a
          href="https://solana.fm/address/8Hb9qMirPhEiGT5TRz7uWTmmLS7YPwUyF2WQVGhiMrNC"
          target="_blank"
          rel="noopener noreferrer"
          style={{ color: '#00FF00' }}
        >
          this link
        </a>
      </Text>
    </Stack>
  </Center>
  </Modal>
  
        <Flex gap="lg" direction="column" align="center" mt="lg">
          <Text size="sm" fw="500">
            Minting Cost: 1 SOL
          </Text>
          <Text size="sm" fw="500">
            By minting this token, you're supporting a cause of goodwill.
          </Text>
          <Text size="sm" fw="500">
            All proceeds will go towards securing legal representation for my upcoming trial in early July.
          </Text>
          <Text size="sm" fw="500">
            The proceeds from this initiative will be derived from the epoch rewards of the Liquid Staking Tokens (LSTs). 
            I have configured the staking pool to allocate all epoch rewards to myself, ensuring maximum benefit.
          </Text>
          <Text size="sm" fw="500">
            There are no mint or redeem fees associated with these tokens, making it a purely charitable contribution. 
            Specifically, the staking pool fees have been set as follows:
          </Text>
          <Text size="sm" fw="500">
            - Epoch Fee: 1% <br />
            - SOL Deposit Fee: 0% <br />
          - Stake Withdrawal Fee: 0% <br />
          - Stake Deposit Fee: 0%
        </Text>
        <Text size="sm" fw="500">
          This setup demonstrates how Liquid Staking Tokens can be utilized for risk-free charity and community support.
        </Text>
        <Text size="sm" fw="500">
          Join us in illustrating the power of blockchain for good, showing that even in challenging times, our community stands strong together.
        </Text>
    
    <Text size="sm" fw="500">
    More details on the trial and how these funds will be used can be found at{' '}
    <a
      href="https://solana.fm/address/8Hb9qMirPhEiGT5TRz7uWTmmLS7YPwUyF2WQVGhiMrNC"
      target="_blank"
      rel="noopener noreferrer"
      style={{ color: '#00FF00' }}
    >
      this link
    </a>
  </Text>
  <Button onClick={openMoreInfoModal}>More Info</Button>
</Flex>
            <Center h="20vh">
              <Text>Connect your wallet to begin.</Text>
              
            </Center>
          </Paper>
        </Container>
      }
    </Container>);
}
